package com.branz.mmorpg.scenes;

public enum SceneCloseReason {
    EXIT,
    INVENTORY_CLOSED,
    DAMAGE,
    HOSTILE_STATE,
    FORCED_MOVEMENT,
    TELEPORT,
    WORLD_CHANGE,
    DEATH,
    DISCONNECT,
    ACTOR_INVALIDATED,
    SESSION_INVALIDATED,
    PLUGIN_DISABLE,
    PROVIDER_FAILURE
}
