package com.branz.mmorpg.scenes;

public enum SceneMode {
    HUB,
    EQUIPMENT,
    WARDROBE_DYE,
    COMBAT_ARTS,
    FORMS,
    MAGIC_ATTUNEMENT,
    CHARACTER_INFORMATION,
    CHARACTER_CREATION,
    APPEARANCE_PREVIEW,
    IMPORTANT_DIALOGUE,
    CUTSCENE,
    FLASK_PREPARATION,
    JOURNAL_PENDING_REWARDS,
    SETTINGS_HELP
}
