name: BranzMMORPG
version: '1.0.0-SNAPSHOT'
main: com.branz.mmorpg.paper.BranzMMORPGPlugin
api-version: '1.21.11'
author: Branz
description: High-performance MMORPG System Plugin for Paper Minecraft
commands:
  branz:
    description: Branz MMORPG administration command
<<<<<<< HEAD
    usage: /branz <reload|status|player>
=======
    usage: /branz <reload|status>
>>>>>>> parent of 3846639 (74)
    permission: branz.admin
permissions:
  branz.admin:
    description: Allows administration of Branz MMORPG
    default: op
